le_utils/constants/exercises.py
I generated a kolibri .pex build with the perseus renderer and tried to run it in ubuntu.
It gave this error:
```
SyntaxError:
Non-ASCII character '\xe2' in kolibri/dist/le_utils/constants/exercises.py on line 20, but no encoding declared;
see http://www.python.org/peps/pep-0263.html for details
```
I tried adding this encoding line, but I'm having trouble testing the solution because I don't fully understand how the build process works.
=> add encoding line

le_utils/constants/languages.py, tests/test_getlangs.py
While looking at this site http://nalibali.org/story-library/multilingual-stories
it became apparent we might need a lookup function for languages by native name.
This PR implements this. See tests for example usage.
Currently only two languages of the ones on nalibali.org are missing so we should add them to our internal json DB: `[u'Sepedi', u'Tshivenda']`
see https://en.wikipedia.org/wiki/Northern_Sotho_language
https://en.wikipedia.org/wiki/Venda_language
already have Venda but the native name is different, so we could add it after a comma.
Modify:
```
"ve":{
"name":"Venda",
"native_name":"Tshivenḓa"
},
```
To:
```
"ve":{
"name":"Venda",
"native_name":"Tshivenḓa, Tshivenda"
},
```
=> Implemented getlang_by_native_name for easier lookups

le_utils/constants/languages.py, le_utils/resources/languagelookup.json, tests/test_getlangs.py
Also edited a few other languages which were inconsitent --- lists of names should be `;`-separated, and reserve `,` for variant.
=> Added Sepedi and missing Tshivenda as discussed in previous PR

le_utils/constants/languages.py, le_utils/resources/languagelookup.json, tests/test_getlangs.py
Before this PR, looking for Spanish by name was retuning Nicaraguan
```
>>> from le_utils.constants.languages import getlang, getlang_by_name, getlang_by_native_name
>>> lang_obj = getlang_by_name('Spanish')
>>> lang_obj.code
'es-NI'
```
There was a bug in the "enrichment" logic (edge case only applies to Spanish) that used the last occurence of the string.
After this PR, the un-localized Spanish gets processed first and so becomes the default:
```
>>> from le_utils.constants.languages import getlang, getlang_by_name, getlang_by_native_name
>>> lang_obj = getlang_by_name('Spanish')
>>> lang_obj.code
'es'
```
The second commit also fixes some inconsistensies in the `native_name` attributes. I enforced the convention that commas separate sifferent native names, and extra attributes in …
=> fix wrong default Spanish lookup by name

le_utils/constants/languages.py, tests/test_languages.py
The `native_name` property of language object is list-like (c.f. [tt](https://github.com/learningequality/le-utils/blob/master/le_utils/resources/languagelookup.json#L689)) and hence not good for showing in user interfaces.
The `first_native_name` property returns the first item in the list (including possible regional  modifiers in brackets).
=> implemented first_native_name helper

le_utils/constants/file_formats.py, tests/test_formats.py
I synced these up and added a test to ensure that all the file extensions listed in `file_formats.choices` are also listed in `formatlookup.json`.
=> keep file_formats.py in sync with formatlookup.json

.gitignore, le_utils/constants/content_kinds.py, le_utils/constants/file_formats.py, le_utils/constants/file_types.py, le_utils/constants/format_presets.py, le_utils/resources/formatlookup.json, le_utils/resources/presetlookup.json, tests/test_formats.py, tests/test_kinds.py, tests/test_presets.py
This is needed to support the two SRT-->VTT conversion PRs:
https://github.com/learningequality/pressurecooker/pull/21
and https://github.com/learningequality/ricecooker/pull/189
The new `convertible_formats` attribute added to the file formats lookup json made me a bit worried that this would cause an error on Studio:
https://github.com/learningequality/studio/blob/develop/contentcuration/contentcuration/management/commands/loadconstants.py#L205-L206
but apparently no, Django models will let you set arbitrary fields on them that don't exist:
```
In [1]: from contentcuration.models import FileFormat
In [7]: ffobj = FileFormat.objects.all()[0]
In [8]: ffobj.__dict__
{'_state': <django.db.models.base.ModelState at 0x10dbb5dd0>,
'extension': u'graphie',
'mimetype': u'.graphie'}
In [9]: …
```
=> Add convertible_formats to format_presets json list

le_utils/constants/file_formats.py, le_utils/resources/formatlookup.json
Revert mimetype changes done in:
https://github.com/learningequality/le-utils/commit/b7e9748d9ba9a2518904821c746ddded01f4aa19#diff-675957a693bce24061dd680105e58225R59
Fixes Studio issue where HTML5App preview is broken.
TODO: revisit mimetypes after move-away-from-Dropzone task started:
https://www.notion.so/learningequality/Move-away-from-Dropzone-for-upload-management-6c3ae1a42a494a2ea3da3bfa4cb2af46
=> Put back dot-ext instead of canonical mimetypes

le_utils/resources/presetlookup.json, setup.py
It looks like the document thumbnail order wasn't updated when we added epubs. As a result, the presets are getting displayed in the wrong order: https://github.com/learningequality/studio/issues/1328
=> Fixed order of document thumbnail

CHANGELOG.md, le_utils/constants/file_formats.py, le_utils/resources/presetlookup.json, setup.py
I will be integrating `pycaption` into `pressurecooker` replacing the `srt2vtt` converter. As a bonus, we'll be able to convert a few other caption file formats, which this PR adds.
=> Add other caption formats supported by pycaption

le_utils/resources/languagelookup.json
Browsers are missing fonts so appears broken, not used 
fixes https://github.com/learningequality/le-utils/issues/56
=> rm old Tagalog string in Baybayin script--

le_utils/constants/file_formats.py, le_utils/resources/presetlookup.json
Just adding 'm4v' extension to the convertible formats. 
Also noticed there is no constant for OGV = "ogv" so I added that
=> Add m4v to convertible_formats

le_utils/constants/languages.py, le_utils/resources/languagelookup.json, tests/test_getlangs.py, tests/test_languages.py
This PR introduces the new language code `zh-Hant` to be used for Traditional Chinese.
Previously we were using `zh-TW` to represent all traditional Chinese characters codes. The `zh-TW` code remains and is to be used only for language codes that match `zh-??-TW`.
The native names were updated to reflect the distinction, and corresponding tests were updated too.
=> Added zh-Hant language code and updated tests

.travis.yml, tox.ini
to match all possibel py-version that migth be used by ricecooker 
(py34 not supported anymore but keeping it for now)
=> Enable py36 and py37 in Travis

setup.py
```
Collecting le-utils==0.1.24 (from -r requirements/base.txt (line 18))
Downloading https://files.pythonhosted.org/packages/f7/5e/e499293c64010ca8e22d126c29b26c3255c41ecc74b7e903e5f1f2a34a54/le-utils-0.1.24.tar.gz
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-build-wjbv6qqa/le-utils/setup.py", line 3, in <module>
long_description = open('README.md').read()
File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2845: ordinal not in range(128)
```
=> Python2 and Python3 compatible README.md read

le_utils/resources/presetlookup.json
- This pr is first step towards completing the [parent pr](https://github.com/learningequality/studio/issues/4081).
- This Pr aims to allow studio to upload .h5p format files and their thumbnails. 
- This is simply done through updating the presetlookup json file.
=> Allow uploads of .h5p content file in Studio

.github/workflows/npm-publish.yml, .pre-commit-config.yaml, scripts/generate_from_specs.py, setup.py
Fixes NPM publishing by ensuring that pre-commit is installed.
Adds a pre-commit hook to regenerate specs to ensure that we are always committing rebuilt files when changing specs.
Excludes this new hook when running the generation script to avoid a potential recursive call.
=> Npm publish and pre commit

js/EmbedTopicsRequest.js, js/package.json, le_utils/constants/embed_topics_request.py, setup.py, spec/schema-embed_topics_request.json, tests/test_schemas.py
This pr adds a level property to the ancestors property in the embed topics schema. `level` is required when a topic has ancestors.
=> Add level property to ancestors

.github/workflows/finalized_specs.yml
Removes use of set-output in line with https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Updates runner to ubuntu-latest for maintainability
=> Update finalized specs check to remove deprecated output and runner

.github/workflows/notify_team_new_comment.yml
With https://github.com/learningequality/.github/pull/11
reusable action is added to .github repo. This PR makes use of it.
Issue: https://github.com/learningequality/kolibri/issues/12567
Create Pull request similar to https://github.com/learningequality/test-actions/pull/53
Create issue and link it to PR
Change default repo branch to the branch you are changing in PR from (1.) due to https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#issue_comment
Post comment in issue.
=> Add notify_team_new_comment github workflow

.github/workflows/community-contribution-labeling.yml
Add GitHub Actions workflow to automatically manage the "community-contribution-in-progress" label on issues based on external contributor assignments. This PR implements the workflow part that calls the shared action from learningequality/.github repository.
Addresses learningequality/kolibri#12923
- **Description:** Add automated workflow for managing community contribution labels when issues are assigned/unassigned to external contributors
- **Products impact:** none
- **Addresses:** learningequality/kolibri#12923
- **Components:** -
- **Breaking:** no 
- **Impacts a11y:** no
- **Guidance:** -
1. Assign any issue to someone
2. Verify the community contribution label is automatically added
3. Unassign the issue
4. Verify the label is automatically removed
Added a workflow file that:
- …
=> Community contribution labeling

.github/workflows/pythontest.yml
* Update skip checking to be within matrix to allow required checks to show as skipped.
* Separate out EOL Python version tests to run in docker to use ubuntu-latest runner.
Fix for le-utils part of https://github.com/learningequality/kolibri-ecosystem/issues/41
Do all tests still pass?
Note, this changes the name of some required tests, so it will so some checks as pending when they are really not. When this has been merged, we should update the required checks for this repo.
=>  Drop use of deprecated and soon to be removed ubuntu-20.04 Github Actions runner

js/package.json, setup.cfg, setup.py
* Changes seemingly invalid metadata key to `long_description` using the `file: ` modifier as per https://setuptools.pypa.io/en/latest/userguide/declarative_config.html#specifying-values
* Bumps version for new release
Errors in Python tests/builds in Kolibri on Python 3.12+ e.g. https://app.readthedocs.org/projects/kolibri-dev/builds/27618651/
Hopefully the tests passing should be sufficient here?
=> Change metadata key to avoid parsing errors.

.github/workflows/unassign-inactive.yaml
This PR implements a GitHub Action to automatically unassign inactive issues based on a predefined period of inactivity. This action will help maintain cleaner issue assignments and prevent outdated issues from cluttering the project.
[#12837](https://github.com/learningequality/kolibri/issues/12837)
```
on:
schedule:
- cron: "1 0 * * 1" 
workflow_dispatch:
```
Action is scheduled to run every monday at 00:01 UTC
=> unassign inactive users action

js/EmbedContentRequest.js, js/EmbedTopicsRequest.js, js/package.json, le_utils/constants/embed_content_request.py, le_utils/constants/embed_topics_request.py, setup.py, spec/schema-embed_content_request.json, spec/schema-embed_topics_request.json, tests/test_schemas.py
- Adds mandatory `channel_id` to the schemas, particularly important for the content embedding requests
- Ensured all IDs are now enforced as UUIDs (with dashes), which will require updates in Studio and CA API to add / remove dashes
- Enforces `language` is passed in topic embedding requests, and removes duplicitous ancestor definition to prioritize the one definition on the target topic
closes https://github.com/learningequality/le-utils/issues/158
Test updates make sense?
=> Update embed schemas for newly required fields
