learningequality/le-utils

setup.py
=> Fix long description.

setup.py
=> Upgrade to 0.0.2

MANIFEST.in, setup.py
The README was not being bundled in.
=> Bundle in README

le_utils/constants/exercises.py, le_utils/constants/file_formats.py, le_utils/constants/format_presets.py, setup.py
Added constants to support content curation
=> More Constants

le_utils/constants/content_kinds.py, le_utils/constants/file_types.py
Define constants for all file types supported by ricecooker API
Needed to support: https://github.com/learningequality/ricecooker/pull/125
=> Define constants for all file types

CHANGELOG.md, README.md, setup.py
Could use some more docs, but this will do for now.
=> Package housekeeping and CHANGELOG

le_utils/constants/languages.py, le_utils/resources/languagelookup.json, scripts/direction_guessed.rb, tests/test_getlangs.py
Intended uses:
- render previews of content nodes in RTL languages correctly on Studio
- annotate with language direction content nodes at export time
=> List of RTL language codes

le_utils/resources/languagelookup.json
Needed for certain content items being cheffed
=> Add language codes be-tarask, hrx, pms, sco, rue

CHANGELOG.md, le_utils/resources/languagelookup.json
this is needed for Aftican Storybook chef
=> First pass of most popular languages

le_utils/constants/content_kinds.py, le_utils/resources/kindlookup.json
=> Add quiz kind.

js/Modalities.js, js/package.json, le_utils/constants/modalities.py, setup.py, spec/constants-modalities.json
=> Add Survey modality

.pre-commit-config.yaml, le_utils/resources/languagelookup.json, requirements-lint.txt
=> Add new languages

.github/workflows/pypi-publish.yml
https://github.com/learningequality/le-utils/actions/runs/5799592321
=> Update publish workflow

.github/dependabot.yml, js/package.json, setup.py
Adds dependabot config
Bumps version to 0.2.6
=> Cleanup and release 0.2.6

.github/workflows/finalized_specs.yml, .github/workflows/pre-commit.yml, .github/workflows/pythontest.yml
Limit checks to run on push on main, and on all PRs.
=> Do better path match checking for python tests.

.github/workflows/pythontest.yml, js/package.json, requirements-test.txt, setup.py, tox.ini
Cleanup version support and test matrix.
Fixes #142
=> Add support for Python 3.13.

.github/workflows/update-pr-spreadsheet.yml
Refer to https://github.com/learningequality/kolibri/pull/12950
=> Remove 'pull_request_review' event from the community contributions spreadsheet action

le_utils/resources/presetlookup.json
This pr updates the document format preset order based on this [pr](https://github.com/learningequality/studio/pull/4872/files#r1998922775)
Tracked by https://github.com/learningequality/studio/pull/4872
- Check that the document format presets have no conflicting order
=> Updates document format preset order

requirements-test.txt
=> Remove unused test dependency.

.github/workflows/manage_issue_header.yml, README.md
- Turns on isssue header automation
- References new contributing guidelines from README.md
=> Turn on issue header automation and reference new contributing guidelines

.github/workflows/call-manage-issue-header.yml
A companion to https://github.com/learningequality/.github/pull/28
=> Update manage issue header workflow events
